### ISSUE TITLE
ADS Setting Error

### ISSUE THREAD

**Issue by amritacreate** [Virtual-Labs/engineers-forum#200]
The following error is coming while doing ADS settings,

Traceback (most recent call last):
  File "src/controller_server.py", line 150, in <module>
    http_server.listen(options.port)
  File "/usr/lib/python2.6/site-packages/tornado-4.1-py2.6-linux-x86_64.egg/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/usr/lib/python2.6/site-packages/tornado-4.1-py2.6-linux-x86_64.egg/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "<string>", line 1, in bind

**Comment by ecthiender** [comment]
Can you include the full error message. Like the exact error message along
with the traceback.

**Comment by amritacreate** [comment]
[root@centos1 ovpl]# ./manage_services.sh stop
./manage_services.sh: line 119: kill: (13395) - No such process
Stopped all services.
[root@centos1 ovpl]# ./manage_services.sh
mongodb: unrecognized service
service mongod is not running
mongodb: unrecognized service
stopping mongod
./manage_services.sh: line 162: mongodb: command not found
restarting mongod
mongodb: unrecognized service
service mongod successfully restarted
Starting all services.
http logging service started
localhost:8239
localhost:8239
/root/logs/ovpl.log
[D 150912 20:49:25 git_commands:26] GIT_CLONE_LOC = /root/labs/
[D 150912 20:49:25 git_commands:27] LAB_SPEC_DIR = /scripts/
[D 150912 20:49:25 git_commands:28] LAB_SPEC_FILE = labspec.json
[D 150912 20:49:25 adapter_server:92] module_name = centos_openvz_adapter, adapter_name = CentOSVZAdapter
[D 150912 20:49:25 centos_openvz_adapter:239] centos_openvz_adapter: test_logging()
[D 150912 20:49:25 adapter_server:104] __main__() PORT=8080, CreateURI=/api/1.0/vm/create, DestroyURI=/api/1.0/vm/destroy,RestartURI=/api/1.0/vm/restart
localhost:8239
localhost:8239
[D 150912 20:49:26 controller_server:149] ControllerServer: It will run on port : 8080
Traceback (most recent call last):
  File "src/controller_server.py", line 150, in <module>
    http_server.listen(options.port)
  File "/usr/lib/python2.6/site-packages/tornado-4.1-py2.6-linux-x86_64.egg/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/usr/lib/python2.6/site-packages/tornado-4.1-py2.6-linux-x86_64.egg/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "<string>", line 1, in bind

**Comment by khushpreet-kaur** [comment]
Looks like 'mongodb' is not installed on your machine.
Have you executed centos_prepare_ovpl.sh scripts to install all the
dependencies for ADS?

[root@centos1 ovpl]# ./manage_services.sh stop
./manage_services.sh: line 119: kill: (13395) - No such process
Stopped all services.
[root@centos1 ovpl]# ./manage_services.sh
mongodb: unrecognized service
service mongod is not running
mongodb: unrecognized service
stopping mongod
./manage_services.sh: line 162: mongodb: command not found
restarting mongod
mongodb: unrecognized service
service mongod successfully restarted
Starting all services.
http logging service started
localhost:8239
localhost:8239
/root/logs/ovpl.log
[D 150912 20:49:25 git_commands:26] GIT_CLONE_LOC = /root/labs/
[D 150912 20:49:25 git_commands:27] LAB_SPEC_DIR = /scripts/
[D 150912 20:49:25 git_commands:28] LAB_SPEC_FILE = labspec.json
[D 150912 20:49:25 adapter_server:92] module_name = centos_openvz_adapter,
adapter_name = CentOSVZAdapter
[D 150912 20:49:25 centos_openvz_adapter:239] centos_openvz_adapter:
test_logging()
[D 150912 20:49:25 adapter_server:104] *main*() PORT=8080,
CreateURI=/api/1.0/vm/create,
DestroyURI=/api/1.0/vm/destroy,RestartURI=/api/1.0/vm/restart
localhost:8239
localhost:8239
[D 150912 20:49:26 controller_server:149] ControllerServer: It will run on
port : 8080
Traceback (most recent call last):
File "src/controller_server.py", line 150, in
http_server.listen(options.port)
File
"/usr/lib/python2.6/site-packages/tornado-4.1-py2.6-linux-x86_64.egg/tornado/tcpserver.py",
line 125, in listen
sockets = bind_sockets(port, address=address)
File
"/usr/lib/python2.6/site-packages/tornado-4.1-py2.6-linux-x86_64.egg/tornado/netutil.py",
line 145, in bind_sockets
sock.bind(sockaddr)
File "", line 1, in bind

—
Reply to this email directly or view it on GitHub
<https://github.com/Virtual-Labs/engineers-forum/issues/200#issuecomment-139744836>
.

**Comment by amritacreate** [comment]
After the successful running of the ./manage_services.sh start LOGGER command, the log displays by tail -f /root/logs/ovpl.log and  got the message 'It will run on port : 8080'. When we are trying to access it by localhost:8080, the page will redirect to 'http://www.ads-server-public-ip.com:8080/' and server not found error produced.

**Comment by khushpreet-kaur** [comment]
Can you tell what IP have you given for both APP_URL and SERVER_IP in
config.json?

On Mon, Sep 14, 2015 at 9:43 AM, Amrita CREATE <notifications@github.com>
wrote:

> After the successful running of the ./manage_services.sh start LOGGER
> command, the log displays by tail -f /root/logs/ovpl.log and got the
> message 'It will run on port : 8080'. When we are trying to access it by
> localhost:8080, the page will redirect to '
> http://www.ads-server-public-ip.com:8080/' and server not found error
> produced.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Virtual-Labs/engineers-forum/issues/200#issuecomment-139958073>
> .
>



-- 
Khushpreet

**Comment by amritacreate** [comment]
http://192.168.100.12:8080/, this is the APP_URL and SERVER_IP that we have given in config.json file. When we are trying to access localhost:8080 in the browser, the following error will return

 Verified data from Persona: {u'status': u'failure', u'reason': u'assertion has expired'}
Traceback (most recent call last):
  File "/usr/lib64/python2.6/logging/handlers.py", line 1054, in emit
    h.endheaders()
  File "/usr/lib64/python2.6/httplib.py", line 930, in endheaders
    self._send_output()
  File "/usr/lib64/python2.6/httplib.py", line 802, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.6/httplib.py", line 761, in send
    self.connect()
  File "/usr/lib64/python2.6/httplib.py", line 742, in connect
    self.timeout)
  File "/usr/lib64/python2.6/socket.py", line 567, in create_connection
    raise error, msg
error: [Errno 110] Connection timed out
[D 150914 17:24:50 controller_server:104] Persona returned error. Aborting authentication.
[I 150914 17:25:53 web:1825] 200 POST /login (::1) 190479.46ms
[I 150914 17:25:53 web:1825] 302 GET / (::1) 0.25ms
[I 150914 17:25:53 web:1825] 200 POST /logout (::1) 0.59ms
[I 150914 17:25:53 web:1825] 302 GET / (::1) 0.24ms
[I 150914 17:25:53 web:1825] 304 GET /login (::1) 1.97ms
[I 150914 17:25:53 web:1825] 304 GET /login (::1) 1.46ms
[I 150914 17:25:53 web:1825] 302 GET / (::1) 0.17ms
[I 150914 17:25:53 web:1825] 304 GET /login (::1) 2.17ms

**Comment by ambikakaul** [comment]
Have you added authorized users in your config folder ?

To do so :

1. Go to config directory.

2. cp sample_authorized_users.py authorized_users.py

3. Edit the authorized_users.py to add valid users

**Comment by amritacreate** [comment]
We have already added valid users. This error is coming on login process.

**Comment by ecthiender** [comment]
If you have given http://192.168.100.12:8080/ as the APP_URL, then you have to access with that URL in your browser and not localhost:8080

**Comment by amritacreate** [comment]
The error coming while executing the given ip with url (http://192.168.100.12:8080/).

**Comment by ecthiender** [comment]
Can you share your config.json file?

**Comment by amritacreate** [comment]
{
    "ENVIRONMENT": {
        "HTTP_PROXY":"",
        "HTTPS_PROXY":""
    },

    "CONTROLLER_CONFIG": {
        "SERVER_PORT": 8080,
        "COOKIE_SECRET": "Text Text Text",
        "PERSONA_VERIFIER": "https://verifier.login.persona.org/verify",
        "APP_URL": "http://192.168.100.12:8080",
        "LOG_FILENAME": "/root/logs/ovpl.log"
    },

    "LABMANAGER_CONFIG": {
        "GIT_CLONE_LOC":"/root/labs/",
        "LAB_SPEC_DIR":"/scripts/",
        "LAB_SPEC_FILE":"labspec.json"
    },

    "VMMANAGER_CONFIG": {
        "DISK_USAGE_URI":"/api/1.0/disk-usage",
        "MEMORY_USAGE_URI":"/api/1.0/mem-usage",
        "RUNNING_TIME_URI":"/api/1.0/running-time",
        "RUNNING_PROCESSES_URI":"/api/1.0/running-processes",
        "CPU_LOAD_URI":"/api/1.0/cpu_load",
        "EXECUTE_URI":"/api/1.0/execute/([\\w*\\d*\\%\\-]+)",
        "TEST_LAB_URI":"/api/1.0/test-lab",
        "SERVER_PORT":9089
    },

    "VMPOOL_CONFIGURATION": {
      "__comment__":"used by vm pool manager",
        "ADAPTER_ENDPOINTS": {
            "CREATE_URI":"/api/1.0/vm/create",
            "DESTROY_URI":"/api/1.0/vm/destroy",
            "RESTART_URI":"/api/1.0/vm/restart"
        },
        "VMPOOLS": [
            {
                "POOLID":1,
                "DESCRIPTION":"LINUX",
                "ADAPTERIP":"http://192.168.100.12",
                "PORT":"8080",
                "__comment__":"adapters in this pool, module & class",
                "ADAPTERS": [
                    {"ADAPTERID" : 1, "MODULE" : "aws_adapter", "ADAPTER" : "AWSAdapter"}, 
                    {"ADAPTERID" : 2, "MODULE" : "centos_openvz_adapter", "ADAPTER" : "CentOSVZAdapter"},
                    {"ADAPTERID" : 3, "MODULE" : "centos_bridged_adapter", "ADAPTER" : "CentOSBridgeVZAdapter"}
                ]
            },
            {
                "POOLID":2,
                "DESCRIPTION":"WINDOWS",
                "ADAPTERIP":"http://localhost",
                "PORT":"8000"
            },
            {
                "POOLID":3,
                "DESCRIPTION":"AMAZONS3",
                "ADAPTERIP":"http://localhost",
                "PORT":"8000"
            },
            {
                "POOLID":4,
                "DESCRIPTION":"AMAZONEC2",
                "ADAPTERIP":"http://localhost",
                "PORT":"8000"
            }
        ]
    },

    "__comment__" : "pick the adapter to use , this will be moved to base.config in the adapters folder",
     "ADAPTER_TO_USE" : {"POOLID" : 1, "ADAPTERID" : 2},

    "LOGGING_CONFIGURATION": {
        "__comment__" : "level 10=DEBUG, 20=INFO, 30=WARNING, 40=ERROR, 50=CRITICAL",
        "LOG_LEVEL":10 ,
        "LOGSERVER_CONFIGURATION": {
            "SERVER_IP": "192.168.100.12",
            "SERVER_PORT": 8239,
            "URI_ENDPOINT": "/log/",
            "FILE_PATH": "/root/logs/"
        }
    }
}

**Comment by ecthiender** [comment]
|ADAPTERIP should be " http://localhost" only. Change ADAPTERIP to be 
"http://localhost".

So with that config.json, restart the services:
 > `./manage-services.sh stop`
 > `./manage-services.sh start`

and then navigate to ||http://192.168.100.12:8080 in your browser, and 
click the login button.

So now, what error do you get?

Apologies, for probably asking again. It was not clear from your 
previous comments, what error happened when. Now with this config file, 
and by going to http://192.168.100.12:8080 and clicking on login, can 
you tell what error you are getting?

|||
On Monday 14 September 2015 03:11 PM, Amrita CREATE wrote:
>
> {
> "ENVIRONMENT": {
> "HTTP_PROXY":"",
> "HTTPS_PROXY":""
> },
>
> |"CONTROLLER_CONFIG": { "SERVER_PORT": 8080, "COOKIE_SECRET": "Text 
> Text Text", "PERSONA_VERIFIER": 
> "https://verifier.login.persona.org/verify", "APP_URL": 
> "http://192.168.100.12:8080", "LOG_FILENAME": "/root/logs/ovpl.log" }, 
> "LABMANAGER_CONFIG": { "GIT_CLONE_LOC":"/root/labs/", 
> "LAB_SPEC_DIR":"/scripts/", "LAB_SPEC_FILE":"labspec.json" }, 
> "VMMANAGER_CONFIG": { "DISK_USAGE_URI":"/api/1.0/disk-usage", 
> "MEMORY_USAGE_URI":"/api/1.0/mem-usage", 
> "RUNNING_TIME_URI":"/api/1.0/running-time", 
> "RUNNING_PROCESSES_URI":"/api/1.0/running-processes", 
> "CPU_LOAD_URI":"/api/1.0/cpu_load", 
> "EXECUTE_URI":"/api/1.0/execute/([\\w*\\d*\\%\\-]+)", 
> "TEST_LAB_URI":"/api/1.0/test-lab", "SERVER_PORT":9089 }, 
> "VMPOOL_CONFIGURATION": { "__comment__":"used by vm pool manager", 
> "ADAPTER_ENDPOINTS": { "CREATE_URI":"/api/1.0/vm/create", 
> "DESTROY_URI":"/api/1.0/vm/destroy", 
> "RESTART_URI":"/api/1.0/vm/restart" }, "VMPOOLS": [ { "POOLID":1, 
> "DESCRIPTION":"LINUX", "ADAPTERIP":"http://192.168.100.12",|
|ADAPTERIP should be only http://localhost|

**Comment by amritacreate** [comment]
This is what we get after changing the ADAPTERIP to "http://localhost".

![screenshot](https://cloud.githubusercontent.com/assets/11895447/9847806/59faf30e-5af9-11e5-9302-f94ce876f5cb.png)

**Comment by sanchita-dixit** [comment]
@amritacreate Any updates on whether the issue has been resolved or it still persists?

**Comment by pushpdeep** [comment]
@amritacreate kindly respond if its resolved. it will help clear issues backlog for the VLEAD team
