### ISSUE TITLE
error while calling ovpl make file

### ISSUE THREAD

**Issue by praveenscreate** [Virtual-Labs/engineers-forum#21]
Am getting an error while calling src/make file of ovpl master

this is the error am getting

[root@centos src]#  make
killall python2 #HACK!
python2: no process killed
make: [stop-server] Error 1 (ignored)
python2 adapters/AdapterServer.py &
python2 ControllerServer.py &
[root@centos src]# Traceback (most recent call last):
  File "ControllerServer.py", line 24, in <module>
    import Controller
  File "/home/Praveen/Downloads/ovpl-master/src/Controller.py", line 11, in <module>
    import LabManager
  File "/home/Praveen/Downloads/ovpl-master/src/LabManager.py", line 8, in <module>
    import requests
ImportError: No module named requests
Traceback (most recent call last):
  File "adapters/AdapterServer.py", line 95, in <module>
    module = __import__(adapter_name)
  File "/home/Praveen/Downloads/ovpl-master/src/adapters/CentOSVZAdapter.py", line 41, in <module>
    import sh
ImportError: No module named sh

**Comment by ecthiender** [comment]
To start ADS you should type: `make start-server`

To stop ADS you should type: `make stop-server`

**Comment by travula** [comment]
mport requests
ImportError: No module named requests

python module 'requests' is not installed. You could try running 'pip
install requests'
